name: release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instala o Poetry
        uses: snok/install-poetry@v1

      - name: Build Package
        run: poetry build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          if-no-files-found: error

    pypi-release:
    name: Publish on PyPI
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/sampyling
    permissions:
        id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
